apiVersion: v1
kind: Service
metadata:
  name: mts-influxdb
spec:
  type: ClusterIP
  selector:
    app: mts-influxdb
  ports:
    - name: influxdb-8083
      port: 8083
    - name: influxdb-8086
      port: 8086
    - name: influxdb-25826
      port: 25826