apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-kafka03-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: mts-kafka03-pod
      labels:
        app: mts-kafka03
    spec:
      containers:
        - name: mts-kafka03-ctn
          image: bitnami/kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: mts-zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:30203
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:30203
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            #- name: KAFKA_BROKER_ID
            #  value: "3"
          ports:
            - containerPort: 30203
          volumeMounts:
            - name: mts-kafka03-vol
              mountPath: /bitnami/kafka/data

      volumes:
        - name: mts-kafka03-vol
          hostPath:
            type: DirectoryOrCreate
            path: /D/mt-volumes/kafka03-data

  selector:
    matchLabels:
      app: mts-kafka03