apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-kafka01-deploy
spec:
  replicas: 3
  template:
    metadata:
      name: mts-kafka01-pod
      labels:
        app: mts-kafka01
    spec:
      containers:
        - name: mts-kafka01-ctn
          image: bitnami/kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: mts-zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:30201
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:30201
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          ports:
            - containerPort: 30201
          volumeMounts:
            - name: mts-kafka01-vol
              mountPath: /bitnami/kafka/data

      volumes:
        - name: mts-kafka01-vol
          hostPath:
            type: DirectoryOrCreate
            path: /D/mt-volumes/kafka01-data

  selector:
    matchLabels:
      app: mts-kafka01