apiVersion: v1
kind: Service
metadata:
  name: mts-kafka-ndport
spec:
  type: NodePort
  selector:
    app: mts-kafka
  ports:
    - name: kafka0
      port: 30200
      nodePort: 30200

    - name: kafka1
      port: 30201
      nodePort: 30201
      
    - name: kafka2
      port: 30202
      nodePort: 30202
