apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ubuntu-set
spec:
  replicas: 1
  serviceName: "my-ubuntu-svc"
  template:
    metadata:
      name: my-ubuntu-pod
      labels:
        app: my-ubuntu
    spec:
      containers:
        - name: my-ubuntu-ctn
          image: my-ubuntu
          imagePullPolicy: Never
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: teste
              value: "meu-teste"
            - name: adv
              valueFrom:
                configMapKeyRef: 
                  name: mts-kafka-config
                  key: advertised.listener
  selector:
    matchLabels:
      app: my-ubuntu